import { SelectOption } from 'interfaces';

export enum PET_REPRODUCTION_TYPES {
  STERILIZED = 'STERILIZED',
  NOT_STERILIZED = 'NOT_STERILIZED',
  NEUTERED = 'NEUTERED',
  NOT_NEUTERED = 'NOT_NEUTERED',
}

export const LOCALE_PET_REPRODUCTION_TYPES = {
  [PET_REPRODUCTION_TYPES.STERILIZED]: 'Стерилизована',
  [PET_REPRODUCTION_TYPES.NOT_STERILIZED]: 'Не стерилизована',
  [PET_REPRODUCTION_TYPES.NEUTERED]: 'Кастрирован',
  [PET_REPRODUCTION_TYPES.NOT_NEUTERED]: 'Не кастрирован',
};

export const PET_REPRODUCTION_TYPES_OPTIONS: SelectOption[] = [
  { label: LOCALE_PET_REPRODUCTION_TYPES.STERILIZED, value: PET_REPRODUCTION_TYPES.STERILIZED },
  { label: LOCALE_PET_REPRODUCTION_TYPES.NOT_STERILIZED, value: PET_REPRODUCTION_TYPES.NOT_STERILIZED },
  { label: LOCALE_PET_REPRODUCTION_TYPES.NEUTERED, value: PET_REPRODUCTION_TYPES.NEUTERED },
  { label: LOCALE_PET_REPRODUCTION_TYPES.NOT_NEUTERED, value: PET_REPRODUCTION_TYPES.NOT_NEUTERED },
];
